import Head from 'next/head'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import React from 'react'


export default function bookVenue() {
  return (
    <>
      <Head>
        <title>Book Venue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      {/* header */}
      <Header />

      {/* main content */}
      {/* banner */}
      <section className="venue-banner py-12 sm:px-12 px-5">
        <div className="venue grid grid-cols-2">
          <div className="left">
            <div className="p-5 bg-yellow-300">
              <h2 className='font-alike md:text-4xl text-2xl text-gray-800 mb-3'>At 18 Candleriggs we make it happen</h2>
              <img src="/images/venue-1.jpg" alt="venue 1" />
            </div>
          </div>
          <div className="right mt-[100px] ml-[-100px] z-[-1]">
            <div className="p-5 bg-green-900">
              <img src="/images/venue-2.jpg" alt="venue 2" />
              <h2 className='font-alike md:text-4xl text-2xl text-yellow-300 mt-3'>At 18 Candleriggs we make it happen</h2>
            </div>
          </div>
        </div>
      </section>

      {/* book */}
      <section className="book sm:px-12 px-6 py-8">
        <h2 className="text-center text-2xl sm:text-3xl font-semibold mb-12">Book venue</h2>

        <div className="book-details grid md:grid-cols-2 grid-cols-1 gap-6 mt-6">
          <div></div>
          <div className='bg-black/60 p-6'>
            <p className='text-white text-sm mb-3 leading-8'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi, tempora reiciendis voluptatum quae cupiditate est molestiae modi fugit amet quisquam voluptatibus magnam aut voluptatem illo consectetur? Ad ut velit necessitatibus.</p>
            <p className='text-white text-sm mb-3 leading-8'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi, tempora reiciendis voluptatum quae cupiditate est molestiae modi fugit amet quisquam voluptatibus magnam aut voluptatem illo consectetur? Ad ut velit necessitatibus.</p>
            <p className='text-white text-sm mb-3 leading-8'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi, tempora reiciendis voluptatum quae cupiditate est molestiae modi fugit amet quisquam voluptatibus magnam aut voluptatem illo consectetur? Ad ut velit necessitatibus.</p>
            <p className='text-white text-sm mb-3 leading-8'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi, tempora reiciendis voluptatum quae cupiditate est molestiae modi fugit amet quisquam voluptatibus magnam aut voluptatem illo consectetur? Ad ut velit necessitatibus.</p>
          </div>
        </div>

        <p className='my-12 text-sm text-black font-semibold text-center'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aut error totam sunt vitae nobis nemo ullam, ut voluptate, eligendi illum dolorem necessitatibus culpa corrupti quia blanditiis dolores animi aliquid quod. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam, veniam consequuntur aspernatur accusantium fuga nobis unde aliquid iusto libero ab odit facilis reiciendis fugiat asperiores voluptatum at magni ducimus iure. Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt sint nemo aliquid? Doloremque iusto magnam, corrupti atque illo neque sed fuga sapiente sunt tempora porro expedita doloribus asperiores laboriosam aperiam.</p>

        <button className='w-auto mx-auto block bg-yellow-300 text-black font-semibold rounded-full px-6 py-2'>Contact Us</button>
      </section>

      {/* bottom section */}
      <section className="py-12 sm:px-12 px-8">
        <div className="grid md:grid-cols-2 gap-6 bg-primary p-8">
          <div className='grid sm:grid-cols-2 grid-cols-1 gap-6'>
            <div>
              <img src="/images/grid-1.png" alt="grid" className='mb-6 w-full sm:h-[350px]' />
              <img src="/images/grid-1-1.png" alt="grid" className='w-full sm:h-[250px]' />
            </div>
            <div>
              <img src="/images/grid-2.png" alt="grid" className='mb-6 w-full sm:h-[250px]' />
              <img src="/images/grid-2-2.png" alt="grid" className='w-full sm:h-[350px]' />
            </div>
          </div>
          <div>
            <img src="/images/grid-2-main.png" alt="grid" className='sm:h-[625px] w-full' />
          </div>
        </div>

      </section>

      {/* footer */}
      <Footer />
    </>
  )
}
