import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'

function Gallery() {
    const [activeTab, setActiveTab] = useState('all')
    
    return (
        <>
            <Head>
                <title>Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo.svg" />
            </Head>

            {/* header */}
            <Header />

            {/* main */}
            <section className="gallery sm:px-12 px-7 py-16">
                <div className="tabs flex justify-center sm:gap-10 gap-3 border-b border-gray-100">
                    <button className={`flex items-center sm:px-6 px-1 gap-2 pb-4 text-black text-[11px] sm:text-[16px] ${activeTab == 'all' ? "border-b-2 border-gray-800" : "border-b-2 border-transparent"}`} onClick={() => {setActiveTab('all')}}>
                        <Image src="/images/all.svg" className="sm:h-6 h-4" alt="all" width={22} height={20} />
                        <span>All</span>
                    </button>
                    <button className={`flex items-center sm:px-6 px-1 gap-2 pb-4 text-black text-[11px] sm:text-[16px] ${activeTab == 'venue' ? "border-b-2 border-gray-800" : "border-b-2 border-transparent"}`} onClick={() => {setActiveTab('venue')}}>
                        <Image src="/images/venue.svg" className="sm:h-6 h-4" alt="venue" width={25} height={24} />
                        <span>Venue</span>
                    </button>
                    <button className={`flex items-center sm:px-6 px-1 gap-2 pb-4 text-black text-[11px] sm:text-[16px] ${activeTab == 'events' ? "border-b-2 border-gray-800" : "border-b-2 border-transparent"}`} onClick={() => {setActiveTab('events')}}>
                        <Image src="/images/events.svg" className="sm:h-6 h-4" alt="events" width={25} height={24} />
                        <span>Events</span>
                    </button>
                    <button className={`flex items-center sm:px-6 px-1 gap-2 pb-4 text-black text-[11px] sm:text-[16px] ${activeTab == 'food' ? "border-b-2 border-gray-800" : "border-b-2 border-transparent"}`} onClick={() => {setActiveTab('food')}}>
                        <Image src="/images/food.svg" className="sm:h-6 h-4" alt="food" width={25} height={24} />
                        <span>Food</span>
                    </button>
                </div>

                {/* tab content */}
                {activeTab == 'all' && (
                    <div className="tab-content mt-12">
                        <div className="grid md:grid-cols-2 grid-cols-1 gap-6">
                            <div className="left">
                                <Image src="/images/gallery-1.png" alt="gallery" className='w-full' width={700} height={675} />
                                <div className="grid sm:grid-cols-2 grid-cols-1 gap-6 mt-8">
                                    <div className="left">
                                        <Image src="/images/gallery-1-2.png" alt="gallery" className='w-full' width={335} height={335} />
                                        <Image src="/images/gallery-1-3.png" alt="gallery" className='w-full mt-8' width={335} height={335} />
                                    </div>
                                    <div className="right">
                                        <Image src="/images/gallery-1-4.png" alt="gallery" className='w-full' width={335} height={335} />
                                        <Image src="/images/gallery-1-5.png" alt="gallery" className='w-full mt-8' width={335} height={335} />
                                    </div>
                                </div>
                            </div>
                            <div className="right">
                                <div className="grid sm:grid-cols-2 grid-cols-1 gap-6">
                                    <div className="left">
                                        <Image src="/images/gallery-2-2.png" alt="gallery" className='w-full' width={335} height={335} />
                                        <Image src="/images/gallery-2-3.png" alt="gallery" className='w-full mt-8' width={335} height={335} />
                                    </div>
                                    <div className="right">
                                        <Image src="/images/gallery-2-4.png" alt="gallery" className='w-full' width={335} height={335} />
                                        <Image src="/images/gallery-2-5.png" alt="gallery" className='w-full mt-8' width={335} height={335} />
                                    </div>
                                </div>
                                <Image src="/images/gallery-2.png" alt="gallery" className='w-full mt-8' width={700} height={675} />
                            </div>
                        </div>

                    </div>
                )}
            </section>
            {/* footer */}
            <Footer />
        </>
    )
}

export default Gallery;
