import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
      weight: ['100', '300', '400', '700', '900'],
      style: ['normal', 'italic'],
      subsets: ['latin'],
    })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        {/* main content */}
        {/* banner */}
        <section className="banner py-20 px-8 sm:px-14">
          <div className="bg-white/20 p-5 rounded">
            <div className="border-2 border-black rounded p-5">
              <h1 className='text-center py-28 text-white text-6xl leading-[65px] font-alike'>The perfect night out in Glasgow ! <br />18 Candleriggs</h1>
            </div>
          </div>
        </section>

        {/* card */}
        <section className="what bg-white py-16 sm:px-14 px-8">
          <div className='flex items-center mb-7'>
            <h2 className='text-3xl text-black font-semibold text-left ml-auto'>What's On At Glasgow's Coolest Event Space.</h2>
            <button className='flex gap-2 items-center ml-auto'>
              <span>View All</span>
              <img src="/images/arrow-right.png" alt="arrow" />
            </button>
          </div>
          <div className="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-8 mt-20 mb-6">
            <div className="card">
              <div className="card-top">
                <img src="/images/card.jpg" alt="card" className='w-full max-h-[400px] object-cover' />
              </div>
            </div>
          </div>

        </section>

        {/* Footer */}
        <Footer />

      </main>
    </>
  )
}
