export const cardData = [
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '10th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: false,
    },
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '15th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: true,
        cancelled: false,
    },
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: true,
    },
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: false,
    },
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: true,
        sold: false,
        cancelled: false,
    },
    {
        image: 'card.jpg',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: false,
    },
    
    
]

export const cardSlidesData = [
    {
        image: 'slide-1.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '10th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: false,
    },
    {
        image: 'slide-2.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '15th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: true,
        cancelled: false,
    },
    {
        image: 'slide-3.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: true,
    },
    
    
]