
export const cardData = [
  {
      id: 1,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '10th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: false,
      sold: false,
      cancelled: false,
  },
  {
      id: 2,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '15th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: false,
      sold: true,
      cancelled: false,
  },
  {
      id: 3,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '30th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: false,
      sold: false,
      cancelled: true,
  },
  {
      id: 4,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '30th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: false,
      sold: false,
      cancelled: false,
  },
  {
      id: 5,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '30th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: true,
      sold: false,
      cancelled: false,
  },
  {
      id: 6,
      image: 'card.jpg',
      title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
      date: '30th December 2023',
      tickets: '$17',
      age: 'All Ages',
      time: 'Show 8pm | Doors 6pm',
      private: false,
      sold: false,
      cancelled: false,
  },
  
  
]

export const imagesData = 

[
    {
        "id": 15286,
        "width": 2500,
        "height": 1667,
        "url": "https://www.pexels.com/photo/person-walking-between-green-forest-trees-15286/",
        "photographer": "Luis del Río",
        "photographer_url": "https://www.pexels.com/@luisdelrio",
        "photographer_id": 1081,
        "avg_color": "#283419",
        "src": {
            "original": "https://images.pexels.com/photos/15286/pexels-photo.jpg",
            "large2x": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "large": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=650&w=940",
            "medium": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350",
            "small": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=130",
            "portrait": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
            "landscape": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "tiny": "https://images.pexels.com/photos/15286/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
        },
        "liked": false,
        "alt": "Person Walking Between Green Forest Trees"
    },
    [
        {
            "id": 3408744,
            "width": 3546,
            "height": 2255,
            "url": "https://www.pexels.com/photo/scenic-view-of-snow-capped-mountains-during-night-3408744/",
            "photographer": "stein egil liland",
            "photographer_url": "https://www.pexels.com/@therato",
            "photographer_id": 144244,
            "avg_color": "#557088",
            "src": {
                "original": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg",
                "large2x": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Scenic View Of Snow Capped Mountains During Night"
        },
        {
            "id": 624015,
            "width": 4216,
            "height": 2848,
            "url": "https://www.pexels.com/photo/aurora-borealis-624015/",
            "photographer": "Frans van Heerden",
            "photographer_url": "https://www.pexels.com/@frans-van-heerden-201846",
            "photographer_id": 201846,
            "avg_color": "#71839F",
            "src": {
                "original": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg",
                "large2x": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/624015/pexels-photo-624015.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Aurora Borealis"
        },
        {
            "id": 572897,
            "width": 6914,
            "height": 4463,
            "url": "https://www.pexels.com/photo/mountain-covered-snow-under-star-572897/",
            "photographer": "eberhard grossgasteiger",
            "photographer_url": "https://www.pexels.com/@eberhardgross",
            "photographer_id": 121938,
            "avg_color": "#5D5A63",
            "src": {
                "original": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg",
                "large2x": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/572897/pexels-photo-572897.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Mountain Covered Snow Under Star"
        },
        
        {
            "id": 3244513,
            "width": 5121,
            "height": 3525,
            "url": "https://www.pexels.com/photo/brown-landscape-under-grey-sky-3244513/",
            "photographer": "Andy Vu",
            "photographer_url": "https://www.pexels.com/@andyhvu",
            "photographer_id": 1653971,
            "avg_color": "#473C36",
            "src": {
                "original": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg",
                "large2x": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/3244513/pexels-photo-3244513.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Brown Landscape Under Grey Sky"
        },
        
    ],
    
    [
        {
            "id": 5708064,
            "width": 7952,
            "height": 5304,
            "url": "https://www.pexels.com/photo/rainbow-on-cloudless-sly-in-nature-5708064/",
            "photographer": "Ben Mack",
            "photographer_url": "https://www.pexels.com/@ben-mack",
            "photographer_id": 3391146,
            "avg_color": "#B9A2A5",
            "src": {
                "original": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg",
                "large2x": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/5708064/pexels-photo-5708064.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Picturesque scenery of colorful rainbow effect on cloudless sky in nature on summer day after rain in countryside"
        },
        {
            "id": 1268129,
            "width": 5760,
            "height": 3840,
            "url": "https://www.pexels.com/photo/pattern-texture-leaf-green-1268129/",
            "photographer": "Markus Spiske",
            "photographer_url": "https://www.pexels.com/@markusspiske",
            "photographer_id": 19851,
            "avg_color": "#3A4D3D",
            "src": {
                "original": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg",
                "large2x": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/1268129/pexels-photo-1268129.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Free stock photo of asymmetry, chlorophyll, color"
        },
        {
            "id": 3064079,
            "width": 3992,
            "height": 2662,
            "url": "https://www.pexels.com/photo/aerial-view-of-landscape-3064079/",
            "photographer": "Mengliu Di",
            "photographer_url": "https://www.pexels.com/@dimengliu",
            "photographer_id": 1368233,
            "avg_color": "#624F3E",
            "src": {
                "original": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg",
                "large2x": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/3064079/pexels-photo-3064079.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Aerial View Of Landscape"
        },
        {
            "id": 3509971,
            "width": 3992,
            "height": 2992,
            "url": "https://www.pexels.com/photo/aerial-photography-of-snow-covered-trees-3509971/",
            "photographer": "Tomáš Malík",
            "photographer_url": "https://www.pexels.com/@tomas-malik-793526",
            "photographer_id": 793526,
            "avg_color": "#647185",
            "src": {
                "original": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg",
                "large2x": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                "large": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
                "medium": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&h=350",
                "small": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&h=130",
                "portrait": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
                "landscape": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
                "tiny": "https://images.pexels.com/photos/3509971/pexels-photo-3509971.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
            },
            "liked": false,
            "alt": "Aerial Photography of Snow Covered Trees"
        },
    ],
    {
        "id": 3591557,
        "width": 3992,
        "height": 2992,
        "url": "https://www.pexels.com/photo/close-up-photo-of-geological-formation-3591557/",
        "photographer": "Tomáš Malík",
        "photographer_url": "https://www.pexels.com/@tomas-malik-793526",
        "photographer_id": 793526,
        "avg_color": "#61646C",
        "src": {
            "original": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg",
            "large2x": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "large": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            "medium": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&h=350",
            "small": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&h=130",
            "portrait": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
            "landscape": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "tiny": "https://images.pexels.com/photos/3591557/pexels-photo-3591557.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280"
        },
        "liked": false,
        "alt": "Close Up Photo of Geological Formation"
    },
    
]

export const cardSlidesData = [
    {
        image: 'slide-1.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '10th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: false,
    },
    {
        image: 'slide-2.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '15th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: true,
        cancelled: false,
    },
    {
        image: 'slide-3.png',
        title: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consect etur adipisicing elit.',
        date: '30th December 2023',
        tickets: '$17',
        age: 'All Ages',
        time: 'Show 8pm | Doors 6pm',
        private: false,
        sold: false,
        cancelled: true,
    },
    
    
]