import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'

export default function Layout({ title, children })
{
	return (
		<>
			<Head>
				<title>{ title }</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/assets/img/favicon.ico" />
			</Head>

			{/* header */}
			<Header />

			{/* main page */ }
			<main>{ children }</main>

			{/* footer */}
			<Footer />

		</>
	)
}