import React from 'react'
import Head from 'next/head'
import Footer from './Footer'
import SecondaryHeader from './SecondaryHeader'

export default function SecondaryLayout({ title, children }) {
    return (
        <>
			<Head>
				<title>{ title }</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/assets/img/favicon.ico" />
			</Head>

			{/* header */}
			<SecondaryHeader />

			{/* main page */ }
			<main>
                { children }
            </main>

			{/* footer */}
			<Footer />

		</>
    )
}
